#!/bin/bash

# Options for the components to install
INSTALL_ZSH=true
INSTALL_OH_MY_ZSH=true
INSTALL_POWERLEVEL10K=true
INSTALL_WEZTERM=true
INSTALL_JETBRAINS_MONO=true
INSTALL_NEOVIM=true
INSTALL_NODEJS=true
INSTALL_STARSHIP=true
INSTALL_VIM_PLUG=true
INSTALL_GNOME_TWEAKS=true
INSTALL_GIT=true

# Git configuration
GIT_USER_NAME="Brett Warren"
GIT_USER_EMAIL="bwarr011@odu.edu"

