- name: Ensure ~/.config exists for dev_user
  become: true
  file:
    path: "/home/{{ dev_user }}/.config"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: '0755'
  tags: [dotfiles, config]

- name: Symlink dotfiles into home directory
  become: true
  file:
    src: "/home/{{ dev_user }}/.dotfiles/.config/{{ item.src }}"
    dest: "/home/{{ dev_user }}/{{ item.dest }}"
    state: link
    force: true
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
  loop:
    - { src: "zsh/.zshrc", dest: ".zshrc" }
    - { src: "tmux/.tmux.conf", dest: ".tmux.conf" }
    - { src: "nvim", dest: ".config/nvim" }
    - { src: "wezterm", dest: ".config/wezterm" }
    - { src: "bat", dest: ".config/bat" }
    - { src: "starship.toml", dest: ".config/starship.toml" }
  tags: [dotfiles, symlink]
