- name: Install and configure Zsh with plugins
  import_tasks: install_zsh.yml
  tags: [zsh, shell]

- name: Set Zsh as default shell
  import_tasks: set_default_shell.yml
  tags: [zsh, shell, default]
