services:

  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: debian12_ansible
    restart: always
    tty: true

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu24_ansible
    restart: always
    tty: true

  fedora:
    build:
      context: .
      dockerfile: Dockerfile.fedora
    container_name: fedora42_ansible
    restart: always
    tty: true

  centos:
    build:
      context: .
      dockerfile: Dockerfile.centos
    container_name: centos10_ansible
    restart: always
    tty: true

  rocky:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    container_name: rocky9_ansible
    restart: always
    tty: true

  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali2025_ansible
    restart: always
    tty: true

  alma:
    build:
      context: .
      dockerfile: Dockerfile.alma
    container_name: alma9_ansible
    restart: always
    tty: true

  rhel:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    container_name: rhel10_ansible
    restart: always
    tty: true