services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ansible_ubuntu
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro  # Mount SSH keys (read-only)
      - ~/.ssh/config:/home/ansible/.ssh/config:ro  # Mount SSH config

  fedora:
    build:
      context: .
      dockerfile: Dockerfile.fedora
    container_name: ansible_fedora
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro
      - ~/.ssh/config:/home/ansible/.ssh/config:ro

  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: ansible_debian
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro
      - ~/.ssh/config:/home/ansible/.ssh/config:ro
