services:

  debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: ansible_debian
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro
      - ~/.ssh/config:/home/ansible/.ssh/config:ro
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ansible_ubuntu
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro  # Mount SSH keys (read-only)
      - ~/.ssh/config:/home/ansible/.ssh/config:ro  # Mount SSH config

  fedora:
    build:
      context: .
      dockerfile: Dockerfile.fedora
    container_name: ansible_fedora
    restart: always
    tty: true
    volumes:
      - ~/.ssh:/home/ansible/.ssh:ro
      - ~/.ssh/config:/home/ansible/.ssh/config:ro

  # centos:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.centos
  #   container_name: ansible_centos
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ~/.ssh:/home/ansible/.ssh:ro
  #     - ~/.ssh/config:/home/ansible/.ssh/config:ro

  # rocky:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.rocky
  #   container_name: ansible_rocky
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ~/.ssh:/home/ansible/.ssh:ro
  #     - ~/.ssh/config:/home/ansible/.ssh/config:ro

  # kali:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.kali
  #   container_name: ansible_kali
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ~/.ssh:/home/ansible/.ssh:ro
  #     - ~/.ssh/config:/home/ansible/.ssh/config:ro

  # alma:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.alma
  #   container_name: ansible_alma
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ~/.ssh:/home/ansible/.ssh:ro
  #     - ~/.ssh/config:/home/ansible/.ssh/config:ro