FROM debian:12

# Install required dependencies
RUN apt update && apt install -y sudo python3 python3-pip ansible

# Create ansible user with sudo privileges
RUN useradd -m ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ansible

# Fix Ansible temporary directory permissions
RUN mkdir -p /tmp/.ansible/tmp && chmod -R 777 /tmp/.ansible

USER ansible
WORKDIR /home/ansible
CMD ["/bin/bash"]
