FROM almalinux:9.5

# Install required dependencies and enable EPEL
RUN dnf install -y sudo python3 python3-pip epel-release && \
    dnf config-manager --set-enabled crb

# Create ansible user with sudo privileges
RUN useradd -m ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ansible

# # Fix Ansible temporary directory permissions
RUN mkdir -p /tmp/.ansible/tmp && chmod -R 777 /tmp/.ansible

USER ansible
WORKDIR /home/ansible
CMD ["/bin/bash"]
