- name: Include EPEL if needed
  import_tasks: enable_epel.ansible.yml
  when: ansible_os_family == "RedHat"
  tags:
    - neovim
    - setup
    - epel

- name: Install Neovim build prerequisites (Debian)
  become: yes
  ansible.builtin.apt:
    name:
      - ninja-build
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - gettext
      - git
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - neovim
    - packages

- name: Install Neovim build prerequisites (RedHat)
  become: yes
  ansible.builtin.yum:
    name:
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc-c++
      - pkgconfig
      - unzip
      - gettext
      - curl
      - git
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - neovim
    - packages

- name: Install Neovim build prerequisites (Arch)
  ansible.builtin.pacman:
    name:
      - base-devel
      - cmake
      - unzip
      - ninja
      - git
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  tags:
    - neovim
    - packages

- name: Install Neovim build prerequisites (MacOS)
  community.general.homebrew:
    name:
      - ninja
      - libtool
      - autoconf
      - automake
      - cmake
      - pkg-config
      - gettext
      - curl
      - git
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - neovim
    - packages

- name: Clone Neovim repository
  become: true
  ansible.builtin.git:
    repo: "{{ nvim_repo_url }}"
    dest: "/usr/local/src/neovim"
    # version: stable
    update: yes
  tags:
    - neovim
    - source
    - git

- block:
    - name: Build Neovim from source
      become: true
      ansible.builtin.command:
        cmd: "make CMAKE_BUILD_TYPE={{ nvim_build_type }}"
        chdir: "/usr/local/src/neovim"
      register: build_result
      changed_when: "'Built target' in build_result.stdout"
      failed_when: build_result.rc != 0
  rescue:
    - name: Fail gracefully if Neovim build fails
      ansible.builtin.fail:
        msg: "Neovim failed to build. Please check the build logs and prerequisites."
  tags:
    - neovim
    - build

- name: Install Neovim
  become: true
  ansible.builtin.command:
    cmd: "make install"
    chdir: "/usr/local/src/neovim"
  tags:
    - neovim
    - install

- name: Fix runtime dir permissions for Neovim
  become: true
  ansible.builtin.file:
    path: "/usr/local/share/nvim/runtime"
    owner: root
    group: root
    mode: "0755"
    recurse: true
  tags:
    - neovim
    - permissions

- name: Ensure /usr/local/share/nvim is world-readable
  become: true
  ansible.builtin.file:
    path: "/usr/local/share/nvim"
    mode: "0755"
  tags:
    - neovim
    - permissions

- name: Verify Neovim installation
  ansible.builtin.command: "nvim --version"
  register: nvim_version
  changed_when: false
  failed_when: nvim_version.rc != 0
  tags:
    - neovim
    - verify

- name: Display Neovim version
  ansible.builtin.debug:
    msg: "{{ nvim_version.stdout }}"
  tags:
    - neovim
    - verify