- name: Create ansible user
  become: yes
  user:
    name: ansible
    groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
    shell: /bin/bash
    create_home: yes

- name: Allow ansible user to run sudo
  become: yes
  copy:
    dest: "/etc/sudoers.d/ansible"
    content: "ansible ALL=(ALL) NOPASSWD: ALL"
    mode: 0440

- name: Install required packages (Debian-based)
  become: yes
  apt:
    name:
      - tmux
      - zsh
      - bat
      - neovim
      - git
    state: present
  when: ansible_os_family == "Debian"

- name: Install required packages (MacOS)
  become: yes
  homebrew:
    name:
      - tmux
      - zsh
      - bat
      - neovim
      - git
    state: present
  when: ansible_os_family == "Darwin"

- name: Install required packages (Fedora-based)
  become: yes
  dnf:
    name:
      - zsh
      - tmux
      - bat
      - neovim
      - git
    state: present
  when: ansible_os_family == "RedHat"

- name: Install OpenSSH server
  become: yes
  package:
    name: openssh-server
    state: present
  when: ansible_connection != "docker"

- name: Enable and start SSH service
  become: yes
  service:
    name: ssh
    state: started
    enabled: true
  when: ansible_connection != "docker"
