---
- name: Remove system-installed Neovim (Debian/Ubuntu)
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  when: ansible_os_family == "Debian"
  tags:
    - neovim
    - cleanup

- name: Remove system-installed Neovim (RedHat/Fedora)
  become: true
  ansible.builtin.dnf:
    name: neovim
    state: absent
  when: ansible_os_family == "RedHat"
  tags:
    - neovim
    - cleanup
