---
- name: Install Podman
  become: true
  tags: [podman, install]
  block:
    - name: Install Podman package
      ansible.builtin.package:
        name: podman
        state: present

    - name: Optionally symlink docker → podman
      ansible.builtin.file:
        src: /usr/bin/podman
        dest: /usr/local/bin/docker
        state: link
      when: docker_symlink_for_podman | default(true)

- name: Verify Podman installation
  become: false
  tags: [podman, verify]
  block:
    - name: Check Podman version
      ansible.builtin.command: podman --version
      register: podman_version
      changed_when: false
      failed_when: podman_version.rc != 0

    - name: Show Podman version
      ansible.builtin.debug:
        msg: "Podman is working: {{ podman_version.stdout }}"
