- name: Install NVM for dev_user (if not present)
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ dev_user }}"
  tags: [nvm, node, setup]

- name: Ensure NVM is loaded in shell for dev_user
  become: true
  blockinfile:
    path: "/home/{{ dev_user }}/{{ shell_config | basename }}"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NVM"
    create: yes
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
  tags: [nvm, node, shell]

- name: Install Node.js using NVM for dev_user
  shell: |
    . "/home/{{ dev_user }}/.nvm/nvm.sh" && nvm install {{ node_version }}
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ dev_user }}"
  tags: [nvm, node, install]
