# Move the directory to the second line
format = '$all$directory$character'

# Don't print a new line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Configure the git status module
[git_status]
style = "bold red"

