vim.opt.encoding = "utf-8"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.termguicolors = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.g.mapleader = " "  -- Space as leader
vim.g.maplocalleader = "\\"  -- Backslash as local leader
