- name: Install fzf binary for dev_user
  become: true
  tags: [fzf, shell, install]
  block:

    - name: Detect system architecture for fzf
      ansible.builtin.command: uname -m
      register: fzf_arch_raw
      changed_when: false

    - name: Set fzf architecture string
      set_fact:
        fzf_arch: "{{ 'arm64' if fzf_arch_raw.stdout | trim in ['aarch64', 'arm64'] else 'amd64' }}"

    - name: Create temporary directory for fzf
      file:
        path: "/tmp/fzf"
        state: directory
        mode: '0755'

    - name: Download fzf binary
      ansible.builtin.get_url:
        url: "https://github.com/junegunn/fzf/releases/download/v0.60.3/fzf-0.60.3-linux_{{ fzf_arch }}.tar.gz"
        dest: "/tmp/fzf/fzf.tar.gz"
        mode: '0644'

    - name: Extract fzf binary
      ansible.builtin.unarchive:
        src: "/tmp/fzf/fzf.tar.gz"
        dest: "/tmp/fzf"
        remote_src: yes

    - name: Move fzf binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/fzf/fzf"
        dest: "/usr/local/bin/fzf"
        mode: '0755'
        remote_src: yes

    - name: Remove fzf tar.gz
      file:
        path: "/tmp/fzf/fzf.tar.gz"
        state: absent
      tags: [cleanup, fzf]

    - name: Remove fzf from /tmp
      file:
        path: "/tmp/fzf/fzf"
        state: absent
      tags: [cleanup, fzf]