---
- name: Install Zoxide
  become: true
  tags: [zoxide, install]
  block:
    - name: Download zoxide installer script
      become: false
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: /tmp/install_zoxide.sh
        mode: "0755"

    - name: Run Zoxide installer
      become: false
      ansible.builtin.shell: |
        set -euo pipefail
        bash /tmp/install_zoxide.sh
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.local/bin/zoxide"

    - name: Move Zoxide binary to /usr/local/bin
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/.local/bin/zoxide"
        dest: /usr/local/bin/zoxide
        mode: "0755"
        remote_src: true
      when: ansible_env.HOME is defined
