- name: Install yamllint for dev_user via pip
  become: true
  become_user: "{{ dev_user }}"
  tags: [yamllint, lint, devtools]
  block:

    - name: Ensure pip is available
      shell: |
        export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
        pyenv which pip || echo "not found"
      args:
        executable: /bin/bash
      register: pip_check
      changed_when: false

    - name: Install yamllint using pip if not already installed
      shell: |
        export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
        pip show yamllint >/dev/null 2>&1 || pip install --user yamllint
      args:
        executable: /bin/bash
      register: yamllint_install
      changed_when: "'Successfully installed' in yamllint_install.stdout or yamllint_install.rc == 0"

    - name: Verify yamllint installation
      shell: |
        export PATH="$HOME/.local/bin:$PATH"
        yamllint --version
      args:
        executable: /bin/bash
      register: yamllint_version
      changed_when: false
      failed_when: yamllint_version.rc != 0

    - name: Display yamllint version
      debug:
        msg: "yamllint version: {{ yamllint_version.stdout }}"
