---
- name: Install starship
  become: true
  block:
    - name: Check if starship is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/starship
      register: starship_binary
      tags: [starship, install]

    - name: Download Starship installer script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install_starship.sh
        mode: "0755"
      when: not starship_binary.stat.exists
      tags: [starship, install]

    - name: Run Starship installer
      ansible.builtin.command: /tmp/install_starship.sh -y
      when: not starship_binary.stat.exists
      changed_when: true
      tags: [starship, install]

    - name: Verify starship installation
      become: false
      ansible.builtin.command: starship --version
      register: starship_version
      changed_when: false
      failed_when: starship_version.rc != 0
      tags: [starship, verify]

    - name: Show installed starship version
      ansible.builtin.debug:
        msg: "Installed starship version: {{ starship_version.stdout }}"
      tags: [starship, verify]
