---
- name: Install tmux
  become: true
  tags: [tmux, install]
  block:
    - name: Ensure tmux is installed via APT (Debian-based)
      ansible.builtin.apt:
        name: tmux
        state: present
        update_cache: true
      register: tmux_apt_result
      failed_when: false
      when: ansible_os_family == "Debian"

    - name: Ensure tmux is installed via DNF/YUM (RedHat-based)
      ansible.builtin.package:
        name: tmux
        state: present
      register: tmux_yum_result
      failed_when: false
      when: ansible_os_family == "RedHat"
