---
- name: Download rustup installer script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "/tmp/rustup-init.sh"
    mode: "0755"
  tags: [rust, install]

- name: Install Rust for dev_user (if not present)
  ansible.builtin.shell: |
    set -euo pipefail
    /tmp/rustup-init.sh -y
  args:
    creates: "/home/{{ dev_user }}/.cargo/bin/rustc"
    executable: /bin/bash
  become: true
  become_user: "{{ dev_user }}"
  tags: [rust, install]

- name: Set default Rust version for dev_user
  ansible.builtin.shell: |
    set -euo pipefail
    source "$HOME/.cargo/env"
    rustup default stable
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ dev_user }}"
  changed_when: true
  tags: [rust, config]
