# Move the directory to the second line
format = '$all'

# Don't print a new line at the start of the prompt
add_newline = false

[username]
show_always = true

[hostname]
ssh_only = false
trim_at = "."

[directory]
truncation_symbol = '.../'
